# Generated by Django 4.1.5 on 2023-01-20 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ormnew', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'категория', 'verbose_name_plural': 'категории'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'товар', 'verbose_name_plural': 'товары'},
        ),
    ]
