# Generated by Django 4.1.5 on 2023-01-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ormnew', '0002_alter_category_options_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.CharField(default=None, max_length=250, verbose_name='Кем_создано'),
            preserve_default=False,
        ),
    ]
