# Generated by Django 4.1.5 on 2023-01-20 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ormnew', '0003_category_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='created_at',
        ),
    ]
